### ISSUE TITLE
Asynchronous Pipes

### ISSUE THREAD

**Issue by Lachee** [Lachee/discord-rpc-csharp#54]
Hey guys, I would love to help you with testing, on my current Linux setup the log produces some errors:

```
INFO: Attempting a new connection
INFO: Attempting to connect to /run/user/1000/discord-ipc-0
ERR : Failed connection to /run/user/1000/discord-ipc-0. Asynchronous pipe mode is not supported
WARN: Tried to close a already closed pipe.
INFO: Attempting to connect to /run/user/1000/discord-ipc-1
ERR : Failed connection to /run/user/1000/discord-ipc-1. Asynchronous pipe mode is not supported
WARN: Tried to close a already closed pipe.
```

And etc, all pipes fail.

_Originally posted by @egordorichev in https://github.com/Lachee/discord-rpc-csharp/issues/53#issuecomment-470088077_

**Comment by Lachee** [comment]
@egordorichev are you using mono? Please give version information on the platform you are using, including os, framework (mono version or dotnet version), and DiscordRpcClient configuration.

**Comment by egordorichev** [comment]
@Lachee I'm using mono + Monogame, I've tested the setup on Ubuntu 16.04 machine, I've tried a bunch of different configs for the library, all taken from the samples. Here is one of them:

```
			client = new DiscordRpcClient("my_id"); // replaced the id
			client.Logger = new ConsoleLogger {
				Level = LogLevel.Info
			};

			client.OnReady += (sender, e) => {
				Log.Info($"Discord RPC loaded, welcome {e.User.Username}!");
			};

			client.Initialize();
			
			client.SetPresence(new RichPresence {
				Details = "A test",
				State = "Trying to work",
				
				Assets = new Assets {
					LargeImageKey = "hero_mercy",
					LargeImageText = "It's woorking!",
					SmallImageKey = "hero_mercy"
				}
			})
```

```
uname -a
Linux rexcellentgames.com 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
> mono --version
Mono JIT compiler version 5.12.0.301
```

```
> dotnet --version
2.1.302
```

And I'm using C# 7, Net Framework 4.7.1.
I'm not sure, but was the library tested on mac? It probably would result in the same issue.

**Comment by Hampusm** [comment]
@egordorichev It's confirmed that it works on Mac. https://github.com/Lachee/discord-rpc-csharp/issues/13#issuecomment-469458832

**Comment by Lachee** [comment]
Can you try including the `NamedPipeClient` from the unity example into your project? Its a work around designed for Unity's Mono and should work in your situation too. You will need the following files:

`Unity Example/Assets/Discord RPC/NamedPipeClient`
This is a custom implementation of NamedPipes that was created as a work around with Unity's asynchronous limitations. Its C++ and can be found [here](https://github.com/Lachee/unity-named-pipes). The unity example has a version already built for 64bit Unix & Windows machines.

`Unity Example/Assets/Discord RPC/Scripts/Control/UnityNamedPipe.cs`
This is a wrapper for the named pipes linked above. This will use `DllImport` on the library and load it up that way. You just need to make sure you tell the `DiscordRpcClient` you are using this in the constructor.

**Comment by egordorichev** [comment]
Sorry that it took me so long, but here are the results:

```
INFO: Connecting to discord-ipc-0
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-1
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-2
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-3
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-4
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-5
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-6
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-7
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-8
ERR : Failed: NativeNamedPipe
INFO: Connecting to discord-ipc-9
ERR : Failed: NativeNamedPipe
ERR : Failed to connect for some reason.

Unhandled Exception:
System.DllNotFoundException: NativeNamedPipe
  at (wrapper managed-to-native) BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream+Native.Close(intptr)
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Disconnect () [0x00001] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:114 
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Dispose (System.Boolean disposing) [0x00017] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:74 
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Finalize () [0x00002] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:66 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: NativeNamedPipe
  at (wrapper managed-to-native) BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream+Native.Close(intptr)
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Disconnect () [0x00001] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:114 
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Dispose (System.Boolean disposing) [0x00017] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:74 
  at BurningKnight.integration.discord.NamedPipeClient.IO.NamedPipeClientStream.Finalize () [0x00002] in /home/egor/Lens/BurningKnight/integration/discord/NamedPipeClient/IO/NamedPipeClientStream.cs:66 
```

(same + exception)

![screenshot from 2019-03-08 17-26-05](https://user-images.githubusercontent.com/7851390/54034171-45fcbf00-41c7-11e9-9fee-5a965e636d19.png)

Interestingly enough, this Connect method is never called, according to my debugger :thinking: 
Here is the constructor call:

```csharp
			client = new DiscordRpcClient("459603244256198657", "", false, -1, new UnityNamedPipe());

```

-1 stands for the first pipe it finds (see DiscordManager.cs)

**Comment by Lachee** [comment]
The DLL needs to be in the root of the project file or what ever your platform recommends. Its using standard `DllImport` without a extension (so it will auto load .so files). If you want to just validate its working you can change the `DllImport`s to use absolute paths instead temporarily

**Comment by egordorichev** [comment]
I've been trying to put them everywhere I could think of, the working directory is `~/Lens/DesktopLinux/bin/Debug`, so dlls are in there too. But nothing seems to do the trick :/

**Comment by egordorichev** [comment]
Ok, little update, sorry that it took so long to figure out. I managed to catch the dll/so file loaded, yet I still can't connect:

`client = new DiscordRpcClient("459603244256198657", -1, null, 128, new UnityNamedPipe());`
![Screenshot from 2019-03-26 14-20-10](https://user-images.githubusercontent.com/7851390/54993175-4d4b0780-4fd2-11e9-8f04-b677b69ea7b1.png)
_client.OnConnectionFailed fired_

**Comment by Lachee** [comment]
Can you try changing your NamedPipeClientStream.cs, line 49 from 
```
        private static readonly string s_pipePrefix = Path.Combine(Path.GetTempPath(), "CoreFxPipe_");
```

to the following:
```

        private static readonly string s_pipePrefix = Path.GetTempPath();
```

**Comment by egordorichev** [comment]
Still the same error:
![Screenshot from 2019-03-27 15-21-45](https://user-images.githubusercontent.com/7851390/55075446-10e7dc00-50a4-11e9-93c7-46c57455526b.png)

Had to make `GetEnviromentTemp()` static to make everything compile.

**Comment by Lachee** [comment]
Are you using Discord from snap?  See issue: https://github.com/discordapp/discord-rpc/issues/213 . To help speed the process along, can you open your discord control panel when you start it (ctrl + shift + i) and tell me what it says near the top for `[RPCServer:IPC]`. For example, running on my VM I get:
`[RPCServer:IPC] Starting on /run/user/1000/snap.discord/discord-ipc-0`

**Comment by Lachee** [comment]
I have commited a fix that should hopefully fix the issue. Just update the NamedPipeClientStream.cs and the UnityNamedPipe.cs from the Unity example project again.

**Comment by egordorichev** [comment]
`
Make sure that neither intellij or discord are installed through snap (software center).
`

JetBrains Rider, IntellijIDEA and Discord are all not installed with snap, I've installed them by hand. 
The pipe exists at the right path.
![Screenshot from 2019-03-28 08-16-35](https://user-images.githubusercontent.com/7851390/55131981-d62c8500-5131-11e9-80eb-b2587bb5ce29.png)

But!

![Screenshot from 2019-03-28 08-25-37](https://user-images.githubusercontent.com/7851390/55132345-22c49000-5133-11e9-94f4-0b2017422d2a.png)

:tada: After applying your patches, everything works. Now I just figure out a relative path to the library, cause I had to hardcode it like this:

```
const string LIBRARY_NAME = "/home/egor/Lens/DesktopLinux/bin/Debug/NativeNamedPipe.so";
```

Thanks for your help, and for the lib :)

**Comment by egordorichev** [comment]
*Can't close the issue, please do that.

**Comment by Lachee** [comment]
Awesome, glad its working again and fixed. I will work on pushing these changes to the nuget.

**Comment by Injazz** [comment]
how long it takes to update nuget?

**Comment by Hampusm** [comment]
> how long it takes to update nuget?

Why do you ask that here? It has nothing to do with any of this.
https://duckduckgo.com/?q=how+long+does+it+take+to+update+nuget&t=h_&ia=qa

**Comment by Injazz** [comment]
sorry, just got the same bug

**Comment by Lachee** [comment]
@Injazz I have just deployed it to nuget now just for you :heart: I was going to wait for a actual release (which I am working towards) but I figured there are significant changes to the library as is that is worth pushing to the nuget. It should be fully deployed in a hour or two at most.

**Comment by FayneAldan** [comment]
I'm unable to get this working on Linux (specifically Zorin OS 12.4). I've tried both a regular and snap install of Discord. My code is located at [FayneAldan/SVRichPresence](/FayneAldan/SVRichPresence). It just says "Asynchronous pipe mode is not supported".

**Comment by Lachee** [comment]
> Can you try including the `NamedPipeClient` from the unity example into your project? Its a work around designed for Unity's Mono and should work in your situation too. You will need the following files:
> 
> `Unity Example/Assets/Discord RPC/NamedPipeClient`
> This is a custom implementation of NamedPipes that was created as a work around with Unity's asynchronous limitations. Its C++ and can be found [here](https://github.com/Lachee/unity-named-pipes). The unity example has a version already built for 64bit Unix & Windows machines.
> 
> `Unity Example/Assets/Discord RPC/Scripts/Control/UnityNamedPipe.cs`
> This is a wrapper for the named pipes linked above. This will use `DllImport` on the library and load it up that way. You just need to make sure you tell the `DiscordRpcClient` you are using this in the constructor.

**Comment by FayneAldan** [comment]
```
Critical app domain exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Lachee.IO.NamedPipeClientStream.Native.Close(IntPtr client)
   at Lachee.IO.NamedPipeClientStream.Disconnect() in C:\Users\ethan\source\repos\SVRichPresence\SVRichPresence\IO\NamedPipeClientStream.cs:line 111
   at Lachee.IO.NamedPipeClientStream.Dispose(Boolean disposing) in C:\Users\ethan\source\repos\SVRichPresence\SVRichPresence\IO\NamedPipeClientStream.cs:line 71
   at Lachee.IO.NamedPipeClientStream.Finalize() in C:\Users\ethan\source\repos\SVRichPresence\SVRichPresence\IO\NamedPipeClientStream.cs:line 63
```

**Comment by FayneAldan** [comment]
I tried to compile 32-bit DLLs and somehow the DLLs I got crashed my computer with a BSoD. Huh. Either way, why do these have to be included separately? Why not include the C# files in the package and still have the C binaries in a separate download?

**Comment by Lachee** [comment]
> I tried to compile 32-bit DLLs and somehow the DLLs I got crashed my computer with a BSoD. Huh. Either way, why do these have to be included separately? Why not include the C# files in the package and still have the C binaries in a separate download?

Main reason is so people dont just use the UnityNamedPipeClient stream without knowing what they are doing and complaining when it doesnt work. Another reason is that it gives users a way to change how they load the native dll with `DllImport` as some people may have some issues locating where they should be.

I will investigate the possiblity of putting the UnityNamedPipeClientStream into the library directly however, as it does seem like a accessibility and ease of use improvement. Thanks for the suggestion.

**Comment by egordorichev** [comment]
Hey, sorry, could you also put `unity-named-pipes` on nuget? I have some really annoying issues with loading dlls, so it would help a lot just to reference nuget package :)

**Comment by egordorichev** [comment]
Like, `DllImport("NativeNamedPipes")` looks to be working on both Mac and Windows without any issues, if I just put the .dll/.so file in the same directory, as .exe. But for Linux this doesn't seem the case, I had to tell it full path to get it working, but thats a tmp solution, I'm trying to figure out, how to point it correctly on Linux. Any ideas? :X
